mmp_meetings:
    resource: "@mmpMeetingsBundle/Resources/config/routing.xml"
    prefix:   /

mmp_user:
    resource: "@mmpUserBundle/Resources/config/routing.xml"
    prefix:   /

mmp_rjp:
    resource: "@mmpRjpBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"