<?php

namespace mmp\rjpBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Collections\ArrayCollection;
use mmp\rjpBundle\Entity\Election;

/**
 * DistrictRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistrictRepository extends EntityRepository
{   
    public function findOneByElections($rules, $order = null) {
        $em = $this->getEntityManager();

        $district = $this->findOneBy($rules, $order);

        $electionsIds = array();
        foreach($district->getCandidates() as $candidate) {
            $electionsIds[$candidate->getElection()->getId()] = $candidate->getElection();
        }
        // $electionsIds = array_keys($electionsIds);        

        foreach($electionsIds as $election) {
            // $electionNew = new Election;
            // $electionNew->setId($election->getId());

            $qdb = $em->getRepository('mmpRjpBundle:Candidate')->createQueryBuilder('c');            
            $qdb->join('c.user', 'u')->addSelect('u');
            $qdb->where('c.district = :district AND c.election = :election');

            $qdb->setParameters([
                'district' => $district->getId(),
                'election' => $election
            ]);
            // $qdb->setParameter('election', $election);
            $candidates = $qdb->getQuery()->getResult();            
            $election->getCandidates()->clear();
            foreach($candidates as $candidate) {
                $election->addCandidate($candidate);
            }
            $district->addElection($election);
        } 

        return $district;
    }
    public function findAllWithLeaders() {
        $districts = $this->findBy([], [
            'slug'  =>  'asc'
        ]);

        foreach($districts as $key => $district) {
            $qdb = $this->getEntityManager()->getRepository('mmpRjpBundle:Councilor')->createQueryBuilder('c');
            $qdb->join('c.candidate', 'ct')->addSelect('ct');
            $qdb->join('ct.user', 'u')->addSelect('u');
            $qdb->where('c.district = :district');
            $qdb->setParameter('district', $district);
            $qdb->orderBy('ct.votes', 'DESC');
            $qdb->setMaxResults(3);

            $counilors = $qdb->getQuery()->getResult();
            if(!$counilors) {
                unset($districts[$key]);
            }

            $district->setCouncilors(new ArrayCollection($counilors));
        }

        return $districts;
    }
    public function findAllDistrictsWithDetails() {
        $districts = $this->findBy([], [
            'slug' => 'asc'
        ]);
        
        foreach($districts as $district) {
            $qdb = $this->getEntityManager()->getRepository('mmpRjpBundle:Councilor')->createQueryBuilder('c');            
            $qdb->join('c.candidate', 'ct')->addSelect('ct');
            $qdb->join('ct.user', 'u')->addSelect('u');
            $qdb->where('c.district = :district');
            $qdb->setParameter('district', $district);
            $qdb->orderBy('u.last_name', 'ASC');
            
            $district->setCouncilors(new ArrayCollection($qdb->getQuery()->getResult()));
        }

        return $districts;
    }
}
