<?php

namespace mmp\rjpBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * DistrictRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistrictRepository extends EntityRepository
{   
    public function findAllWithLeaders() {
        $districts = $this->findBy([], [
            'slug'  =>  'asc'
        ]);

        foreach($districts as $key => $district) {
            $qdb = $this->getEntityManager()->getRepository('mmpRjpBundle:Councilor')->createQueryBuilder('c');
            $qdb->join('c.candidate', 'ct')->addSelect('ct');
            $qdb->join('ct.user', 'u')->addSelect('u');
            $qdb->where('c.district = :district');
            $qdb->setParameter('district', $district);
            $qdb->orderBy('ct.votes', 'DESC');
            $qdb->setMaxResults(3);

            $counilors = $qdb->getQuery()->getResult();
            if(!$counilors) {
                unset($districts[$key]);
            }

            $district->setCouncilors(new ArrayCollection($counilors));
        }

        return $districts;
    }
    public function findAllDistrictsWithDetails() {
        $districts = $this->findBy([], [
            'slug' => 'asc'
        ]);
        
        foreach($districts as $district) {
            $qdb = $this->getEntityManager()->getRepository('mmpRjpBundle:Councilor')->createQueryBuilder('c');            
            $qdb->join('c.candidate', 'ct')->addSelect('ct');
            $qdb->join('ct.user', 'u')->addSelect('u');
            $qdb->where('c.district = :district');
            $qdb->setParameter('district', $district);
            $qdb->orderBy('u.last_name', 'ASC');
            
            $district->setCouncilors(new ArrayCollection($qdb->getQuery()->getResult()));
        }

        return $districts;
    }
}
