<?php

namespace mmp\rjpBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ElectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElectionRepository extends EntityRepository
{
    public function findByDistrict() {
        
    }
}
